### ISSUE TITLE
[Pelagus] - Add Send Confirmation

### ISSUE THREAD

**Issue by mibuono** [PelagusWallet/pelagus-extension#159] opened 2024-03-25 20:13 UTC
When a user goes to send a transaction, they should be able to see basic outputs of the transaction so that they know they aren't spending all of their money.

During Sends, the user should see confirmation of transaction initiated.

**Comment by rileystephens28** [comment] 2024-05-16 13:56
Duplicate of #250

**Closed as completed by rileystephens28** 2024-05-16 13:56 UTC
Labels: enhancement, ui-change
